### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by mogira** [mogira/MP4Pythonista#2]
- [x] Divide UI directory to the external repository
- [ ] Prohibit DoubleTap zoom and PinchOut zoom completely
- [ ] Add the option, fullsize view(popup) or tabview on pythonista
- [ ] Improve the speed to show jacket image
- [ ] Change view of objc_util.ui into WKWebview and viewcontroller
<br /><br />
- [ ] Divide commonly used functions from UI.js
- [ ] Add title and artist information on UI
- [ ] Add volume controller on UI
